[pt]
title = "Suziboy"
description = "Descrição"
weight = 1
LanguageName = "PT"
contentDir = "content/pt" 

[en]
title = "Suziboy"
description = "Description"
weight = 2
LanguageName = "EN"
contentDir = "content/en"
