  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Sobre"
  weight = 300
  identifier = "sobre"
  url = "/sobre/"

  [[main]]
  name = "Contato"
  weight = 400
  identifier = "contato"
  url = "/contato/"

  [[footer]]
  name = "copyright"
  weight = 1
  identifier = "copyright"
  url = "/copyright/"