baseurl = "http://example.org/"
languageCode = "en-us"
title = "Suzano Bitencourt"
theme = "hugo-cards"
#themesDir = "../.."

[pagination]
  pagerSize = 6

[params]
  builtBy = "bool"
  defaultImage = "gopher.jpg"

  facebook = ""
  twitter = ""
  quora = "https://pt.quora.com/profile/suzano"
  github = "https://github.com/suzano"
  email = "suzanobitencourt@gmail.com"

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  disqus = "http://disqus.com/by/suzanobitencourt"
  
  custom_css = ["css/custom.css"]

  #[params.post.meta]
  #  isHidden = true

  #[params.post.sidebar]
  #  type = "profile"
  #  title = "Profile"

  [params.analytics]
    type="UA"
    trackingID = ""

  [params.copyright]
     name = "bool"
     link = "https://bool.netlify.com"

